### ISSUE TITLE
Plugin Not Working

### ISSUE THREAD

**Issue by Glizzy8488** [RoguedBear/BetterDiscordPlugin-AutoIdleOnAFK#46]
The plugin no longer puts me in idle. I have it set to go idle after 5 minutes, but it does nothing. I have tried updating betterdiscord, and have updated the plugin to v0.4.0, but the issue still persists. How can I fix this?

https://imgur.com/a/EoJOAgr

**Comment by RoguedBear** [comment]
If the issue still persists, would you mind sharing sharing the screenshot of the settings page for the plugin?
I have tried to reproduce the issue on my end to see if something broke, but for me the plugin is changing the status when i am AFK.

What are the steps that lead to your status not being changed so that i could reproduce the issue on my end

**Comment by Glizzy8488** [comment]
Here is the settings page:
https://imgur.com/a/azmu49j

I'm not sure how to reproduce this issue, but what I did to test the issue, was setting a timer for 5 mins, clicking on another window, and then not moving my mouse. I have tried disconnecting my controller, which seemed to be an issue with discord's  orginal idle timer, but it didn't help.

I'm not really sure what else I can tell you, but I'm happy to answer any other questions

**Comment by RoguedBear** [comment]
i also did the same thing to test the plugin on my end, here were my steps:
- set status to online, and recheck what my settings were 
- closed discord to taskbar and was working for a while
- i opened discord after 5 minutes my status was invisible. 


i am not sure if this will help your case or not, but can you also update ZeresPluginLibrary to 2.0.17 manually? atleast that will restore some of the missing settings options

If this doesn't work I might have to send you a debug version of the plugin on DM which have logs enabled

**Comment by Glizzy8488** [comment]
I couldn't find ZeresPluginLibrary v2.0.17, but I do have v2.0.16 installed

**Comment by RoguedBear** [comment]
the v2.0.17 version is available here: https://github.com/rauenzi/BDPluginLibrary/tree/master/release
if that doesn't work i'll ask you to send the contents of `AutoIdleOnAFK.config.json` in the plugin directory and send you the debug version of plugin with logging enabled.

**Comment by Glizzy8488** [comment]
I downloaded v2.0.17, but the issue still persisted. 

Here is the AutoIdleOnAFK.config.json file you requested:
https://www.mediafire.com/file/jdxa3wr6blkk2vn/AutoIdleOnAFK.config.json/file

**Comment by RoguedBear** [comment]
uhm, are you able to open that file on your side in notepad?
the file you have provided appears to be corrupted, i can not open it. there doesn't appear to be any text data in the file.

[PS: you can drag and drop files and paste images from clipboard to add them as attachments in your issue comments from within github itself]

**Comment by Glizzy8488** [comment]
Oh, I didn't realise, thanks.

Heres the image you requested:

![Screenshot 2023-06-09 195630](https://github.com/RoguedBear/BetterDiscordPlugin-AutoIdleOnAFK/assets/135643416/f6d158e8-284a-4f6b-8fc0-0f92c3484838)

**Comment by RoguedBear** [comment]
i think this is where the problem is stemming from. your config file is corrupted for some reason.
your config file should be containing this textual data:
![image](https://github.com/RoguedBear/BetterDiscordPlugin-AutoIdleOnAFK/assets/39442192/d452f0d0-6497-4e19-b0e3-7f3d3156e81a)
it looks like the plugin couldnt read the settings values and might be erroring out hence  why nothing was happening.

should be a simple fix, you can delete that config file and BetterDiscord should create a new one for you when you open it.

**Comment by Glizzy8488** [comment]
Yep, that fixed the issue, thanks
